# @name Create one chat

POST {{URL_CHAT}} HTTP/1.1
connection: keep-alive
content-type: application/json

[{"name": "test_name"}]

###
# @name Get chat by id

GET {{URL_CHAT}}?id=1 HTTP/1.1
connection: keep-alive
host: localhost:8080

###
# @name Get all chats

GET {{URL_CHAT}} HTTP/1.1
connection: keep-alive
host: localhost:8080
