# @name Check client for password

POST http://localhost:8080/api/db/users?type=check HTTP/1.1
content-type: application/json
connection: keep-alive

[{
    "login": "test_login",
    "password": "test_password"
}]

###
# @name create one client

POST http://localhost:8080/api/db/users HTTP/1.1
content-type: application/json
connection: keep-alive

[{
    "login": "test_login",
    "username": "test_username",
    "password": "test_password"
}]

###
# @name Get all

GET http://localhost:8080/api/db/users HTTP/1.1
accept: */*
host: localhost:8080

###
# @name Get by id

GET http://localhost:8080/api/db/users?id=1 HTTP/1.1
connection: keep-alive
