# @name Create one message
POST http://localhost:8080/api/db/messages HTTP/1.1
content-type: application/json

[{
    id: 0,
    chatId: chat.id,
    authorId: user.id,
    text: "Hello",
    createdAt: ""
}]
